name: grostore
description: Grostore Flutter App
publish_to: 'none'
version: 1.2.0+2

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  route_transitions: ^2.0.1
  shared_value: ^3.0.0
  http: ^0.13.5
  intl_phone_number_input: ^0.7.3+1
  toast: ^0.3.0
  go_router: ^7.0.0
  carousel_slider: ^5.0.0
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  dotted_line: ^3.1.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2
  image_picker: ^0.8.9
  intl: ^0.19.0
  html: ^0.15.6
  html_unescape: ^2.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename: ^2.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/landing_logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/flags/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_gen:
  synthetic-package: false
